version: '3'

volumes:
  postgres_data: {}
  
services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: games_api
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8080:8080"

  postgres:
    image: postgres:10.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
