# Generated by Django 2.2 on 2019-08-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('score', models.FloatField(verbose_name='Score')),
                ('genre', models.CharField(max_length=100, null=True, verbose_name='Genre')),
                ('editors_choice', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='N', max_length=1, verbose_name="Editors' Choice")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
